<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240225183207 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE gksphone_insto_likes DROP FOREIGN KEY FK_gksphone_insto_likes_gksphone_insto_instas');
        $this->addSql('ALTER TABLE gksphone_insto_likes DROP FOREIGN KEY FK_gksphone_insto_likes_gksphone_insto_accounts');
        $this->addSql('ALTER TABLE twitter_tweets DROP FOREIGN KEY FK_twitter_tweets_twitter_accounts');
        $this->addSql('ALTER TABLE gksphone_group_message DROP FOREIGN KEY FK_phonegroupmessage');
        $this->addSql('ALTER TABLE gksphone_twitter_tweets DROP FOREIGN KEY FK_gksphone_twitter_tweets_gksphone_twitter_accounts');
        $this->addSql('ALTER TABLE gksphone_insto_story DROP FOREIGN KEY FK_gksphone_insto_story_gksphone_insto_accounts');
        $this->addSql('ALTER TABLE gksphone_insto_instas DROP FOREIGN KEY FK_gksphone_insto_instas_gksphone_insto_accounts');
        $this->addSql('ALTER TABLE gksphone_twitter_likes DROP FOREIGN KEY FK_gksphone_twitter_likes_gksphone_twitter_accounts');
        $this->addSql('ALTER TABLE gksphone_twitter_likes DROP FOREIGN KEY FK_gksphone_twitter_likes_gksphone_twitter_tweets');
        $this->addSql('ALTER TABLE twitter_likes DROP FOREIGN KEY FK_twitter_likes_twitter_tweets');
        $this->addSql('ALTER TABLE twitter_likes DROP FOREIGN KEY FK_twitter_likes_twitter_accounts');
        $this->addSql('DROP TABLE mdt_profiles');
        $this->addSql('DROP TABLE gksphone_insto_likes');
        $this->addSql('DROP TABLE ak4y_donatesystem');
        $this->addSql('DROP TABLE nclothes');
        $this->addSql('DROP TABLE addon_account_data');
        $this->addSql('DROP TABLE gksphone_tinderacc');
        $this->addSql('DROP TABLE gksphone_messages');
        $this->addSql('DROP TABLE datastore');
        $this->addSql('DROP TABLE user_licenses');
        $this->addSql('DROP TABLE baninfo');
        $this->addSql('DROP TABLE mdt_incidents');
        $this->addSql('DROP TABLE gksphone_job_message');
        $this->addSql('DROP TABLE twitter_tweets');
        $this->addSql('DROP TABLE kc_warns');
        $this->addSql('DROP TABLE gksphone_mails');
        $this->addSql('DROP TABLE mdt_vehicles');
        $this->addSql('DROP TABLE gksphone_group_message');
        $this->addSql('DROP TABLE phone_app_chat');
        $this->addSql('DROP TABLE addon_inventory');
        $this->addSql('DROP TABLE open_car');
        $this->addSql('DROP TABLE gksphone_vehicle_sales');
        $this->addSql('DROP TABLE gksphone_settings');
        $this->addSql('DROP TABLE billing');
        $this->addSql('DROP TABLE gksphone_calls');
        $this->addSql('DROP TABLE twitter_accounts');
        $this->addSql('DROP TABLE mdt_config');
        $this->addSql('DROP TABLE mdt_reports');
        $this->addSql('DROP TABLE okokvehicleshop_saleshistory');
        $this->addSql('DROP TABLE mdt_evidences');
        $this->addSql('DROP TABLE gksphone_gotur');
        $this->addSql('DROP TABLE jobs');
        $this->addSql('DROP TABLE mdt_warrants');
        $this->addSql('DROP TABLE gksphone_bank_transfer');
        $this->addSql('DROP TABLE addon_inventory_items');
        $this->addSql('DROP TABLE gksphone_twitter_tweets');
        $this->addSql('DROP TABLE gksphone_insto_story');
        $this->addSql('DROP TABLE gksphone_app_chat');
        $this->addSql('DROP TABLE gksphone_tindermessage');
        $this->addSql('DROP TABLE okokvehicleshop_shops');
        $this->addSql('DROP TABLE gksphone_yellow');
        $this->addSql('DROP TABLE banlisthistory');
        $this->addSql('DROP TABLE gksphone_blockednumber');
        $this->addSql('DROP TABLE licenses');
        $this->addSql('DROP TABLE gksphone_insto_accounts');
        $this->addSql('DROP TABLE gksphone_messages_group');
        $this->addSql('DROP TABLE gksphone_insto_instas');
        $this->addSql('DROP TABLE phone_calls');
        $this->addSql('DROP TABLE banlist');
        $this->addSql('DROP TABLE adr');
        $this->addSql('DROP TABLE addon_account');
        $this->addSql('DROP TABLE inventories');
        $this->addSql('DROP TABLE okokvehicleshop_vehicles');
        $this->addSql('DROP TABLE ak4y_donatesystem_codes');
        $this->addSql('DROP TABLE gangbuilder');
        $this->addSql('DROP TABLE gksphone_users_contacts');
        $this->addSql('DROP TABLE okokvehicleshop_orders');
        $this->addSql('DROP TABLE datastore_data');
        $this->addSql('DROP TABLE job_grades');
        $this->addSql('DROP TABLE players');
        $this->addSql('DROP TABLE phone_users_contacts');
        $this->addSql('DROP TABLE gksphone_gallery');
        $this->addSql('DROP TABLE phone_messages');
        $this->addSql('DROP TABLE coreinventories');
        $this->addSql('DROP TABLE vehicle_sold');
        $this->addSql('DROP TABLE gksphone_twitter_likes');
        $this->addSql('DROP TABLE gksphone_gps');
        $this->addSql('DROP TABLE cj');
        $this->addSql('DROP TABLE twitter_likes');
        $this->addSql('DROP TABLE society_moneywash');
        $this->addSql('DROP TABLE owned_vehicles');
        $this->addSql('DROP TABLE vehicle_categories');
        $this->addSql('DROP TABLE kc_jails');
        $this->addSql('DROP TABLE vehicles');
        $this->addSql('DROP TABLE gksphone_news');
        $this->addSql('DROP TABLE esx_clotheshop');
        $this->addSql('DROP TABLE gksphone_twitter_accounts');
        $this->addSql('DROP TABLE items');
        $this->addSql('DROP TABLE gksphone_tindermatch');
        $this->addSql('ALTER TABLE users MODIFY id INT NOT NULL');
        $this->addSql('DROP INDEX email ON users');
        $this->addSql('DROP INDEX id ON users');
        $this->addSql('DROP INDEX `primary` ON users');
        $this->addSql('ALTER TABLE users DROP email, CHANGE job job VARCHAR(20) DEFAULT \'unemployed\' NOT NULL, CHANGE job_grade job_grade INT DEFAULT 0 NOT NULL, CHANGE `group` `group` VARCHAR(50) DEFAULT \'user\' NOT NULL, CHANGE accounts accounts JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE inventory inventory JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE loadout loadout JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE position position JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE skin skin JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE status status JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE is_dead is_dead TINYINT(1) DEFAULT 0 NOT NULL, CHANGE disabled disabled TINYINT(1) DEFAULT 0 NOT NULL, CHANGE hotbar hotbar JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE roles roles JSON DEFAULT NULL json_valid(`roles`) COMMENT \'(DC2Type:json)\', CHANGE inventorysettings inventorysettings JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE IsHandcuffed IsHandcuffed TINYINT(1) DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE users ADD PRIMARY KEY (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mdt_profiles (identifier VARCHAR(250) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, notes TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, image TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, UNIQUE INDEX citizenid (identifier)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_insto_likes (id INT AUTO_INCREMENT NOT NULL, authorId INT DEFAULT NULL, inapId INT DEFAULT NULL, INDEX FK_gksphone_insto_likes_gksphone_insto_accounts (authorId), INDEX FK_gksphone_insto_likes_gksphone_insto_instas (inapId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ak4y_donatesystem (id INT AUTO_INCREMENT NOT NULL, citizenid VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, credit INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE nclothes (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, skin LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE addon_account_data (id INT AUTO_INCREMENT NOT NULL, account_name VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, money INT NOT NULL, owner VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX index_addon_account_data_account_name (account_name), UNIQUE INDEX index_addon_account_data_account_name_owner (account_name, owner), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_tinderacc (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, username VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, passaword VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, date VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, image VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, gender INT DEFAULT NULL, identifier VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_messages (id INT AUTO_INCREMENT NOT NULL, transmitter VARCHAR(50) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, receiver VARCHAR(50) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, message LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, isRead INT DEFAULT 0 NOT NULL, owner INT DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE datastore (name VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, label VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, shared INT NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_licenses (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, owner VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE baninfo (id INT AUTO_INCREMENT NOT NULL, license VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, identifier VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, liveid VARCHAR(21) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, xblid VARCHAR(21) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, discord VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, playerip VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, playername VARCHAR(32) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mdt_incidents (id INT AUTO_INCREMENT NOT NULL, title TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, description TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, persons TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, officers TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, evidences TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, vehicles JSON NOT NULL COMMENT \'(DC2Type:json)\', criminals TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, date TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, createdby TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_job_message (id INT AUTO_INCREMENT NOT NULL, name LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, number VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, message LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, photo LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, gps VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, owner INT DEFAULT 0 NOT NULL, jobm VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE twitter_tweets (id INT AUTO_INCREMENT NOT NULL, authorId INT NOT NULL, realUser VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, message VARCHAR(256) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, likes INT DEFAULT 0 NOT NULL, INDEX FK_twitter_tweets_twitter_accounts (authorId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE kc_warns (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(100) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, license VARCHAR(100) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, reason VARCHAR(250) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, name VARCHAR(250) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, admin_name VARCHAR(250) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, admin_identifier VARCHAR(100) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, timestamp VARCHAR(50) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_mails (id INT AUTO_INCREMENT NOT NULL, citizenid VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'0\' NOT NULL COLLATE `utf8mb3_general_ci`, sender VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'0\' NOT NULL COLLATE `utf8mb3_general_ci`, subject VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'0\' NOT NULL COLLATE `utf8mb3_general_ci`, image TEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, message TEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mdt_vehicles (plate VARCHAR(10) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, image TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, notes TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, UNIQUE INDEX plate (plate)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_group_message (id INT AUTO_INCREMENT NOT NULL, groupid INT NOT NULL, owner LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ownerphone VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, groupname VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, messages LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, contacts LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX groupid (groupid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE phone_app_chat (id INT AUTO_INCREMENT NOT NULL, channel VARCHAR(20) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, message VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE addon_inventory (name VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, label VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, shared INT NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE open_car (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, label VARCHAR(255) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, value VARCHAR(50) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, got VARCHAR(50) CHARACTER SET latin1 DEFAULT NULL COLLATE `latin1_swedish_ci`, NB INT DEFAULT 0, PRIMARY KEY(id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_vehicle_sales (id INT AUTO_INCREMENT NOT NULL, owner LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, ownerphone VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, plate VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, model VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, price INT NOT NULL, image LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_settings (id INT AUTO_INCREMENT NOT NULL, identifier LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, crypto LONGTEXT CHARACTER SET utf8mb4 DEFAULT \'{}\' NOT NULL COLLATE `utf8mb4_general_ci`, phone_number VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, avatar_url LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE billing (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, sender VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, target_type VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, target VARCHAR(40) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, amount INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_calls (id INT AUTO_INCREMENT NOT NULL, owner LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci` COMMENT \'Num tel proprio\', num LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci` COMMENT \'Num reférence du contact\', incoming INT NOT NULL COMMENT \'Défini si on est à l\'\'origine de l\'\'appels\', time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, accepts INT NOT NULL COMMENT \'Appels accepter ou pas\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE twitter_accounts (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(50) CHARACTER SET utf8mb3 DEFAULT \'0\' NOT NULL COLLATE `utf8mb3_general_ci`, password VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT \'0\' NOT NULL COLLATE `utf8mb4_bin`, avatar_url VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, UNIQUE INDEX username (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mdt_config (identifier VARCHAR(250) CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, theme INT NOT NULL, sidebar INT NOT NULL, UNIQUE INDEX citizenid (identifier)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mdt_reports (id INT AUTO_INCREMENT NOT NULL, type TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, title TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, description TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, persons TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, officers TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, vehicles TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, evidences TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, date TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, createdby TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE okokvehicleshop_saleshistory (shop_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, vehicle_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, vehicle_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, buyer_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, buyer_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, price VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mdt_evidences (id INT AUTO_INCREMENT NOT NULL, imgurl TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, description TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, type TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, date TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, createdby TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_gotur (id INT AUTO_INCREMENT NOT NULL, label LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, price INT DEFAULT 0, count INT NOT NULL, item LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, kapat VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'false\' COLLATE `utf8mb4_general_ci`, adet INT DEFAULT 0, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE jobs (name VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, label VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, whitelisted TINYINT(1) DEFAULT 0 NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mdt_warrants (id INT AUTO_INCREMENT NOT NULL, incident INT NOT NULL, identifier TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, date TEXT CHARACTER SET latin1 NOT NULL COLLATE `latin1_swedish_ci`, approved INT DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_bank_transfer (id INT AUTO_INCREMENT NOT NULL, type INT NOT NULL, identifier LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, price LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, name LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE addon_inventory_items (id INT AUTO_INCREMENT NOT NULL, inventory_name VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, name VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, count INT NOT NULL, owner VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX index_addon_inventory_items_inventory_name_name (inventory_name, name), INDEX index_addon_inventory_inventory_name (inventory_name), INDEX index_addon_inventory_items_inventory_name_name_owner (inventory_name, name, owner), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_twitter_tweets (id INT AUTO_INCREMENT NOT NULL, authorId INT NOT NULL, realUser VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, message VARCHAR(256) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, image LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, likes INT DEFAULT 0 NOT NULL, INDEX FK_gksphone_twitter_tweets_gksphone_twitter_accounts (authorId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_insto_story (id INT AUTO_INCREMENT NOT NULL, authorId INT NOT NULL, realUser LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, stories LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, isRead VARCHAR(256) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, likes INT DEFAULT 0 NOT NULL, INDEX FK_gksphone_insto_story_gksphone_insto_accounts (authorId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_app_chat (id INT AUTO_INCREMENT NOT NULL, channel VARCHAR(20) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, message VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_tindermessage (id INT AUTO_INCREMENT NOT NULL, message TEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, tinderes TEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, owner INT DEFAULT 0 NOT NULL, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE okokvehicleshop_shops (shop_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, shop_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, owner VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, owner_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, money VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, employees LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_yellow (id INT AUTO_INCREMENT NOT NULL, phone_number VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, firstname VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, lastname VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, message LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, image LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE banlisthistory (id INT AUTO_INCREMENT NOT NULL, license VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, identifier VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, liveid VARCHAR(21) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, xblid VARCHAR(21) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, discord VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, playerip VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, targetplayername VARCHAR(32) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, sourceplayername VARCHAR(32) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, reason VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, timeat INT NOT NULL, added VARCHAR(40) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, expiration INT NOT NULL, permanent INT DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_blockednumber (id INT AUTO_INCREMENT NOT NULL, identifier LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, hex LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, number LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE licenses (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_insto_accounts (id INT AUTO_INCREMENT NOT NULL, forename LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, surname LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, username VARCHAR(250) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, password LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, avatar_url LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, takip LONGTEXT CHARACTER SET utf8mb4 DEFAULT \'[]\' COLLATE `utf8mb4_bin`, UNIQUE INDEX username (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_messages_group (id INT AUTO_INCREMENT NOT NULL, owner LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, ownerphone VARCHAR(50) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, groupname VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, gimage LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, contacts LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_insto_instas (id INT AUTO_INCREMENT NOT NULL, authorId INT NOT NULL, realUser LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, message LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, image LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, filters LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, likes INT DEFAULT 0 NOT NULL, INDEX FK_gksphone_insto_instas_gksphone_insto_accounts (authorId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE phone_calls (id INT AUTO_INCREMENT NOT NULL, owner VARCHAR(10) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci` COMMENT \'Num tel proprio\', num VARCHAR(10) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci` COMMENT \'Num reférence du contact\', incoming INT NOT NULL COMMENT \'Défini si on est à l\'\'origine de l\'\'appels\', time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, accepts INT NOT NULL COMMENT \'Appels accepter ou pas\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE banlist (license VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, identifier VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, liveid VARCHAR(21) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, xblid VARCHAR(21) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, discord VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, playerip VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, targetplayername VARCHAR(32) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, sourceplayername VARCHAR(32) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, reason VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, timeat VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, expiration VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, permanent INT DEFAULT 0 NOT NULL, PRIMARY KEY(license)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE adr (id INT AUTO_INCREMENT NOT NULL, author TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, firstname TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, lastname TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, reason TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, dangerosity TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE addon_account (name VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, label VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, shared INT NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE inventories (id BIGINT AUTO_INCREMENT NOT NULL, identifier TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, type VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, data LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE okokvehicleshop_vehicles (vehicle_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, vehicle_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, category VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, stock LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, unlisted LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, min_price VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, max_price VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, owner_buy_price VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ak4y_donatesystem_codes (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, credit INT DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gangbuilder (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, label VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, society VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, posboss VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, posveh VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, poscoffre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, posspawncar VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_users_contacts (id INT AUTO_INCREMENT NOT NULL, identifier LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, number VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, display LONGTEXT CHARACTER SET utf8mb4 DEFAULT \'-1\' COLLATE `utf8mb4_general_ci`, avatar LONGTEXT CHARACTER SET utf8mb3 DEFAULT \'https://cdn.iconscout.com/icon/free/png-256/avatar-370-456322.png\' NOT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE okokvehicleshop_orders (id INT AUTO_INCREMENT NOT NULL, shop_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, shop_type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, vehicle_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, vehicle_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, reward VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, in_progress VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, employee_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, employee_id VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE datastore_data (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, owner VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, data LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX index_datastore_data_name (name), UNIQUE INDEX index_datastore_data_name_owner (name, owner), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE job_grades (id INT AUTO_INCREMENT NOT NULL, job_name VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, grade INT NOT NULL, name VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, label VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, salary INT NOT NULL, skin_male LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, skin_female LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE players (identifier VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'Not Found\' NOT NULL COLLATE `utf8mb4_general_ci`, discord VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'Not Found\' COLLATE `utf8mb4_general_ci`, phone_number VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'0\' COLLATE `utf8mb4_general_ci`, PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE phone_users_contacts (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, number VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, display VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT \'-1\' NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_gallery (id INT AUTO_INCREMENT NOT NULL, hex LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, image LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE phone_messages (id INT AUTO_INCREMENT NOT NULL, transmitter VARCHAR(10) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, receiver VARCHAR(10) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, message VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'0\' NOT NULL COLLATE `utf8mb3_general_ci`, time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, isRead INT DEFAULT 0 NOT NULL, owner INT DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE coreinventories (name VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, data LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE vehicle_sold (plate VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, client VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, model VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, soldby VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(plate)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_twitter_likes (id INT AUTO_INCREMENT NOT NULL, authorId INT DEFAULT NULL, tweetId INT DEFAULT NULL, INDEX FK_gksphone_twitter_likes_gksphone_twitter_tweets (tweetId), INDEX FK_gksphone_twitter_likes_gksphone_twitter_accounts (authorId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_gps (id INT AUTO_INCREMENT NOT NULL, hex LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, nott LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, gps LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE cj (id INT AUTO_INCREMENT NOT NULL, author TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, firstname TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, lastname TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, reason TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE twitter_likes (id INT AUTO_INCREMENT NOT NULL, authorId INT DEFAULT NULL, tweetId INT DEFAULT NULL, INDEX FK_twitter_likes_twitter_accounts (authorId), INDEX FK_twitter_likes_twitter_tweets (tweetId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE society_moneywash (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, society VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, amount INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE owned_vehicles (plate VARCHAR(12) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, owner VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, state TINYINT(1) DEFAULT 0 NOT NULL, vehicle LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, type VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'car\' NOT NULL COLLATE `utf8mb4_unicode_ci`, job VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, `stored` TINYINT(1) DEFAULT 0 NOT NULL, carseller INT DEFAULT 0, PRIMARY KEY(plate)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE vehicle_categories (name VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, label VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE kc_jails (id INT AUTO_INCREMENT NOT NULL, license VARCHAR(100) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, name VARCHAR(100) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, admin_name VARCHAR(100) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, admin_identifier VARCHAR(100) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, time VARCHAR(100) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, time_s VARCHAR(100) CHARACTER SET latin1 DEFAULT \'0\' NOT NULL COLLATE `latin1_swedish_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET latin1 COLLATE `latin1_swedish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE vehicles (model VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, name VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, price INT NOT NULL, category VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(model)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_news (id INT AUTO_INCREMENT NOT NULL, hex LONGTEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, haber LONGTEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, baslik LONGTEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, resim LONGTEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, video LONGTEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, zaman DATETIME DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE esx_clotheshop (id INT AUTO_INCREMENT NOT NULL, owner VARCHAR(300) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, name VARCHAR(50) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, outfit JSON NOT NULL COMMENT \'(DC2Type:json)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_twitter_accounts (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(50) CHARACTER SET utf8mb3 DEFAULT \'0\' NOT NULL COLLATE `utf8mb3_general_ci`, password VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT \'0\' NOT NULL COLLATE `utf8mb4_bin`, avatar_url LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, profilavatar LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, UNIQUE INDEX username (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE items (name VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, label VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, weight INT DEFAULT 1 NOT NULL, rare TINYINT(1) DEFAULT 0 NOT NULL, can_remove TINYINT(1) DEFAULT 1 NOT NULL, x INT DEFAULT 1, y INT DEFAULT 1, category VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'misc\' COLLATE `utf8mb4_general_ci`, componentTint INT DEFAULT NULL, componentHash VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, backpackModel INT DEFAULT NULL, backgroundTexture INT DEFAULT NULL, description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'An item\' NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE gksphone_tindermatch (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT 0 NOT NULL, friend_id INT DEFAULT 0 NOT NULL, is_match INT DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE gksphone_insto_likes ADD CONSTRAINT FK_gksphone_insto_likes_gksphone_insto_instas FOREIGN KEY (inapId) REFERENCES gksphone_insto_instas (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gksphone_insto_likes ADD CONSTRAINT FK_gksphone_insto_likes_gksphone_insto_accounts FOREIGN KEY (authorId) REFERENCES gksphone_insto_accounts (id)');
        $this->addSql('ALTER TABLE twitter_tweets ADD CONSTRAINT FK_twitter_tweets_twitter_accounts FOREIGN KEY (authorId) REFERENCES twitter_accounts (id)');
        $this->addSql('ALTER TABLE gksphone_group_message ADD CONSTRAINT FK_phonegroupmessage FOREIGN KEY (groupid) REFERENCES gksphone_messages_group (id)');
        $this->addSql('ALTER TABLE gksphone_twitter_tweets ADD CONSTRAINT FK_gksphone_twitter_tweets_gksphone_twitter_accounts FOREIGN KEY (authorId) REFERENCES gksphone_twitter_accounts (id)');
        $this->addSql('ALTER TABLE gksphone_insto_story ADD CONSTRAINT FK_gksphone_insto_story_gksphone_insto_accounts FOREIGN KEY (authorId) REFERENCES gksphone_insto_accounts (id)');
        $this->addSql('ALTER TABLE gksphone_insto_instas ADD CONSTRAINT FK_gksphone_insto_instas_gksphone_insto_accounts FOREIGN KEY (authorId) REFERENCES gksphone_insto_accounts (id)');
        $this->addSql('ALTER TABLE gksphone_twitter_likes ADD CONSTRAINT FK_gksphone_twitter_likes_gksphone_twitter_accounts FOREIGN KEY (authorId) REFERENCES gksphone_twitter_accounts (id)');
        $this->addSql('ALTER TABLE gksphone_twitter_likes ADD CONSTRAINT FK_gksphone_twitter_likes_gksphone_twitter_tweets FOREIGN KEY (tweetId) REFERENCES gksphone_twitter_tweets (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE twitter_likes ADD CONSTRAINT FK_twitter_likes_twitter_tweets FOREIGN KEY (tweetId) REFERENCES twitter_tweets (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE twitter_likes ADD CONSTRAINT FK_twitter_likes_twitter_accounts FOREIGN KEY (authorId) REFERENCES twitter_accounts (id)');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE users MODIFY id INT NOT NULL');
        $this->addSql('DROP INDEX `PRIMARY` ON users');
        $this->addSql('ALTER TABLE users ADD email VARCHAR(180) DEFAULT NULL, CHANGE job job VARCHAR(20) DEFAULT \'unemployed\', CHANGE job_grade job_grade INT DEFAULT 0, CHANGE `group` `group` VARCHAR(50) DEFAULT \'user\', CHANGE accounts accounts LONGTEXT DEFAULT NULL, CHANGE inventory inventory LONGTEXT DEFAULT NULL, CHANGE loadout loadout LONGTEXT DEFAULT NULL, CHANGE position position VARCHAR(255) DEFAULT \'{"x":-269.4,"y":-955.3,"z":31.2,"heading":205.8}\', CHANGE skin skin LONGTEXT DEFAULT NULL, CHANGE status status LONGTEXT DEFAULT NULL, CHANGE is_dead is_dead TINYINT(1) DEFAULT 0, CHANGE disabled disabled TINYINT(1) DEFAULT 0, CHANGE hotbar hotbar LONGTEXT DEFAULT NULL, CHANGE roles roles JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE inventorysettings inventorysettings LONGTEXT DEFAULT NULL, CHANGE IsHandcuffed IsHandcuffed TINYINT(1) DEFAULT 0');
        $this->addSql('CREATE UNIQUE INDEX email ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX id ON users (id)');
        $this->addSql('ALTER TABLE users ADD PRIMARY KEY (identifier)');
    }
}
